/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEmpleados;
import Controlador.ControladorEquiposProyecto;
import Controlador.ControladorItemsEmpleado;
import Controlador.ControladorItemsEquipo;
import Controlador.ControladorMiembrosEquipo;
import Dominio.Empleado;
import Dominio.Equipo;
import Dominio.Item;
import Dominio.Proyecto;
import Dominio.Sistema;
import Modelo.ModeloEmpleadosSistema;
import Modelo.ModeloEmpleadosEquipo;
import Modelo.ModeloEquiposProyecto;
import Modelo.ModeloHistoricosItem;
import Modelo.ModeloItemsEmpleado;
import Modelo.ModeloItemsEquipo;
import javax.swing.JOptionPane;

/**
 *
 * @author mauro
 */
public class Admin extends javax.swing.JFrame {
        
    private Proyecto proyecto;
    private Empleado empleado;    
    private ModeloEquiposProyecto modeloEquiposProyecto=new ModeloEquiposProyecto();
    private ModeloEmpleadosEquipo modeloMiembrosEquipo=new ModeloEmpleadosEquipo();
    private ModeloItemsEquipo modeloItems=new ModeloItemsEquipo();
    private ModeloEmpleadosSistema modeloEmpleados=new ModeloEmpleadosSistema();
    private ModeloHistoricosItem modeloHistorico=new ModeloHistoricosItem();
    private ModeloItemsEmpleado modeloItemsRegistrados=new ModeloItemsEmpleado();
    private ControladorMiembrosEquipo controladorMiembrosEquipo;
    private ControladorEquiposProyecto controladorEquiposProyecto;
    private ControladorEmpleados controladorEmpleados;
    private ControladorItemsEquipo controladorItemsEquipo;
    private ControladorItemsEmpleado controladorItemsEmpleado;
    
    private Admin() {
        initComponents();
        
        controladorMiembrosEquipo=new ControladorMiembrosEquipo(jTMiembrosEquipo);
        controladorEquiposProyecto=new ControladorEquiposProyecto(jTEquipos);
        controladorEmpleados=new ControladorEmpleados(jTEmpleados);
        controladorItemsEquipo=new ControladorItemsEquipo(jTItems);
        controladorItemsEmpleado=new ControladorItemsEmpleado(jTItemsRegistrados);
    }
    private static Admin admin=null;

    public static Admin getInstance(){
        if (admin==null) admin=new Admin();
        return admin;
    }    
    public void abrirVentana(Proyecto proyecto, Empleado empleado){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.repaint();
        this.proyecto=proyecto;
        this.empleado=empleado;        
        this.modeloEquiposProyecto.setLista(proyecto);
        modeloItemsRegistrados.setLista(empleado);
        jTItemsRegistrados.repaint();
        jTItemsRegistrados.setDefaultRenderer(Object.class, new RenderizadoCeldas(modeloItemsRegistrados));
        this.modeloEmpleados.setLista(Sistema.getInstance());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTEquipos = new javax.swing.JTable();
        jBCrearEquipo = new javax.swing.JButton();
        jBBorrarEquipo = new javax.swing.JButton();
        jBCrearItem = new javax.swing.JButton();
        jBBorrarItem = new javax.swing.JButton();
        jBAltaEmpleado = new javax.swing.JButton();
        jBBajaEmpleado = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTMiembrosEquipo = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTItems = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEmpleados = new javax.swing.JTable();
        jBCrearEmpleado = new javax.swing.JButton();
        jBBorrarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTItemsRegistrados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTHistoricos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin");
        setMinimumSize(new java.awt.Dimension(980, 449));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTEquipos.setModel(modeloEquiposProyecto
        );
        jTEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEquiposMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTEquipos);

        jBCrearEquipo.setText("Crear equipo");
        jBCrearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCrearEquipoMouseClicked(evt);
            }
        });

        jBBorrarEquipo.setText("Borrar equipo");
        jBBorrarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarEquipoMouseClicked(evt);
            }
        });

        jBCrearItem.setText("Crear item");
        jBCrearItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCrearItemMouseClicked(evt);
            }
        });

        jBBorrarItem.setText("Borrar item");
        jBBorrarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarItemMouseClicked(evt);
            }
        });

        jBAltaEmpleado.setText("Alta empleado");
        jBAltaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAltaEmpleadoMouseClicked(evt);
            }
        });

        jBBajaEmpleado.setText("Baja empleado");
        jBBajaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBajaEmpleadoMouseClicked(evt);
            }
        });

        jSplitPane1.setDividerLocation(300);

        jTMiembrosEquipo.setModel(modeloMiembrosEquipo);
        jScrollPane7.setViewportView(jTMiembrosEquipo);

        jSplitPane1.setRightComponent(jScrollPane7);

        jTItems.setModel(modeloItems);
        jScrollPane6.setViewportView(jTItems);

        jSplitPane1.setLeftComponent(jScrollPane6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCrearEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBBorrarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCrearItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBBorrarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBajaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jBAltaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearEquipo)
                    .addComponent(jBCrearItem)
                    .addComponent(jBAltaEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBorrarEquipo)
                    .addComponent(jBBorrarItem)
                    .addComponent(jBBajaEmpleado))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Proyecto", jPanel3);

        jTEmpleados.setModel(modeloEmpleados);
        jScrollPane1.setViewportView(jTEmpleados);

        jBCrearEmpleado.setText("Crear Empleado");
        jBCrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCrearEmpleadoMouseClicked(evt);
            }
        });

        jBBorrarEmpleado.setText("Borrar Empleado");
        jBBorrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBorrarEmpleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBCrearEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBorrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearEmpleado)
                    .addComponent(jBBorrarEmpleado)))
        );

        jTabbedPane4.addTab("Empleados", jPanel1);

        jSplitPane2.setDividerLocation(300);

        jTItemsRegistrados.setModel(modeloItemsRegistrados);
        jTItemsRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTItemsRegistradosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTItemsRegistrados);

        jSplitPane2.setLeftComponent(jScrollPane2);

        jTHistoricos.setModel(modeloHistorico);
        jScrollPane3.setViewportView(jTHistoricos);

        jSplitPane2.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Items registrados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEquiposMouseClicked
        Equipo equipo=controladorEquiposProyecto.getElemento();
        modeloMiembrosEquipo.setLista(equipo);
        modeloItems.setLista(equipo);       
    }//GEN-LAST:event_jTEquiposMouseClicked

    private void jBCrearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCrearEquipoMouseClicked
        CrearEquipo.getInstance().abrirVentana(controladorEquiposProyecto);        
    }//GEN-LAST:event_jBCrearEquipoMouseClicked

    private void jBCrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCrearEmpleadoMouseClicked
        CrearEmpleado.getInstance().abrirVentana(controladorEmpleados);
    }//GEN-LAST:event_jBCrearEmpleadoMouseClicked

    private void jBBorrarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarEquipoMouseClicked
        
        try{
            controladorEquiposProyecto.borrarElemento();
        }
        
        catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Seleccione un equipo");
        }
        
    }//GEN-LAST:event_jBBorrarEquipoMouseClicked

    private void jBCrearItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCrearItemMouseClicked
        CrearItem.getInstance().abrirVentana(controladorItemsEquipo,empleado,modeloMiembrosEquipo.getElementos());
    }//GEN-LAST:event_jBCrearItemMouseClicked

    private void jBAltaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAltaEmpleadoMouseClicked
        AltaEmpleado.getInstance().abrirVentana(controladorMiembrosEquipo);
    }//GEN-LAST:event_jBAltaEmpleadoMouseClicked

    private void jBBorrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarEmpleadoMouseClicked
        Empleado empleado=controladorEmpleados.getElemento();
        if (!empleado.estáOcupado()) controladorEmpleados.borrarElemento();
        else JOptionPane.showMessageDialog(null, "El usuario está ocupado en un proyecto");
    }//GEN-LAST:event_jBBorrarEmpleadoMouseClicked

    private void jBBorrarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBorrarItemMouseClicked
        controladorItemsEquipo.borrarElemento();
    }//GEN-LAST:event_jBBorrarItemMouseClicked

    private void jBBajaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBajaEmpleadoMouseClicked
        controladorMiembrosEquipo.borrarElemento();
    }//GEN-LAST:event_jBBajaEmpleadoMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Login.getInstance().abrirVentana();
    }//GEN-LAST:event_formWindowClosed

    private void jTItemsRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTItemsRegistradosMouseClicked
       Item item=controladorItemsEmpleado.getElemento();
        item.setVisto();
        jTItemsRegistrados.repaint();
        modeloHistorico.setLista(item);
    }//GEN-LAST:event_jTItemsRegistradosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAltaEmpleado;
    private javax.swing.JButton jBBajaEmpleado;
    private javax.swing.JButton jBBorrarEmpleado;
    private javax.swing.JButton jBBorrarEquipo;
    private javax.swing.JButton jBBorrarItem;
    private javax.swing.JButton jBCrearEmpleado;
    private javax.swing.JButton jBCrearEquipo;
    private javax.swing.JButton jBCrearItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTEmpleados;
    private javax.swing.JTable jTEquipos;
    private javax.swing.JTable jTHistoricos;
    private javax.swing.JTable jTItems;
    private javax.swing.JTable jTItemsRegistrados;
    private javax.swing.JTable jTMiembrosEquipo;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
    

}
