/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorTabla;
import Dominio.Empleado;
import Dominio.Sistema;
import java.util.Objects;

/**
 *
 * @author mauro
 */
public class AltaEmpleado extends javax.swing.JFrame {

    private ControladorTabla controladorTabla;
    
    private static AltaEmpleado altaEmpleado=null;
    
    public static AltaEmpleado getInstance(){
        if (altaEmpleado==null)altaEmpleado=new AltaEmpleado();
        return altaEmpleado;
    }
    
    public void abrirVentana(ControladorTabla controladorTabla){
        this.controladorTabla=controladorTabla;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
        
    public AltaEmpleado() {
        initComponents();
    }
    private static boolean esValido(String cadena){
    	Boolean esValido=true;
        try{Long.parseLong(cadena,10);} 
        catch(NumberFormatException nfe){esValido=false;}
        return esValido;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFLegajo = new javax.swing.JTextField();
        jBCargar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta empleado");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Legajo:");

        jBCargar.setText("Cargar");
        jBCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCargarMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCargar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(jBCancelar))
                    .addComponent(jTFLegajo)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCargar)
                    .addComponent(jBCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCargarMouseClicked
        if (esValido(jTFLegajo.getText())){
            Long l=Long.parseLong(jTFLegajo.getText());
            for (Empleado empleado : Sistema.getInstance().getEmpleados()) {
                if (Objects.equals(empleado.getId(), l)){
                    if(!empleado.estáOcupado()){
                        controladorTabla.addElemento(empleado);
                        dispose();
                        break;
                    }
                    
                }            
            }
        }
    }//GEN-LAST:event_jBCargarMouseClicked

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jTFLegajo.setText("");
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFLegajo;
    // End of variables declaration//GEN-END:variables
}
