/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dominio.Empleado;
import Dominio.Estado;
import Dominio.Item;
import Modelo.ModeloLista;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mauro
 */
public class CambiarEstado extends javax.swing.JFrame {

    private static CambiarEstado cambiarEstado=null;
    private Empleado usuario;
    private ModeloLista<Estado> modeloEstados=new ModeloLista();
    private ModeloLista<Empleado> modeloEmpleados=new ModeloLista();
    private Item item;
    private ArrayList<Estado> listaEstados;
    private ArrayList<Empleado> listaEmpleados;
    
    public static CambiarEstado getInstance(){
        if (cambiarEstado==null) cambiarEstado=new CambiarEstado();
        return cambiarEstado;
    }
    
    private CambiarEstado() {
        initComponents();
    }
    
    public void abrirVentana(Item i, Empleado usuario){
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.item=i;
        this.usuario=usuario;
        listaEstados=i.getEstadoActual().obtenerSiguientes();
        listaEmpleados=i.getEquipo().obtenerMiembros();
        modeloEstados.setElementos(listaEstados);
        modeloEmpleados.setElementos(listaEmpleados);
        jCBResponsable.updateUI();
        jCBEstado.updateUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBResponsable = new javax.swing.JComboBox<>();
        jCBEstado = new javax.swing.JComboBox<>();
        jBCambiar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar estado");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Estado nuevo:");

        jLabel2.setText("Nuevo responsable:");

        jCBResponsable.setModel(modeloEmpleados);

        jCBEstado.setModel(modeloEstados);

        jBCambiar.setText("Cambiar");
        jBCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCambiarMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBResponsable, 0, 126, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCambiar)
                    .addComponent(jBCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCambiarMouseClicked
        int indexEstado=jCBEstado.getSelectedIndex();
        int indexResponsable=jCBResponsable.getSelectedIndex();
        
        if ((indexEstado!=-1) && (indexResponsable!=-1)){
            Estado estado=listaEstados.get(indexEstado);
            Empleado responsable=listaEmpleados.get(indexResponsable);
            item.cambiarEstado(estado, responsable,usuario);
            Responsable.getInstance().actualizarItem();
            dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Campos no válidos");
    }//GEN-LAST:event_jBCambiarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jCBResponsable.setSelectedIndex(-1);
        jCBEstado.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCambiar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JComboBox<String> jCBResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
