/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorTabla;
import Dominio.Empleado;
import Dominio.Equipo;
import Dominio.Item;
import Dominio.Sistema;
import Dominio.Tipo;
import Modelo.ModeloLista;
import java.util.ArrayList;
/**
 *
 * @author mauro
 */
public class CrearItem extends javax.swing.JFrame {

    private static CrearItem crearItem=null;
    private Equipo equipo;
    private Empleado empleado;
    private ModeloLista<Tipo> modeloTipos=new ModeloLista();
    private ModeloLista<Empleado> modeloEmpleados=new ModeloLista();
    private ArrayList<Tipo> listaTipos=new ArrayList();
    
    private ControladorTabla controladorItems;
    private ControladorTabla controladorEmpleados;
    
    public static CrearItem getInstance(){
        if (crearItem==null) crearItem=new CrearItem();
        return crearItem;
    }
    
    
    private CrearItem() {
        initComponents();
    }

    public void abrirVentana(ControladorTabla controladorItems,Empleado empleado,ArrayList<Empleado> listaEmpleados){
        listaTipos=Sistema.getInstance().getTipos();
        modeloTipos.setElementos(listaTipos);
        modeloEmpleados.setElementos(listaEmpleados);
        this.controladorItems=controladorItems;
        this.empleado=empleado;
        setVisible(true);
        this.setLocationRelativeTo(null);
    }
        
    private boolean esNumérico(String cadena){
    	try{
            Long.parseLong(cadena,10);
            return true;
    	} 
        catch(NumberFormatException nfe){
            return false;
    	}
    }
    
    public boolean esValido(){
        Boolean esValido=true;
        if ("".equals(jTFNombre.getText())) esValido=false;
        if (!esNumérico(jTFId.getText())) esValido=false;
        if (jCBTipo.getSelectedIndex()==-1) esValido=false;
        if (jCBResponsable.getSelectedIndex()==-1) esValido=false;
        return esValido;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFId = new javax.swing.JTextField();
        jCBTipo = new javax.swing.JComboBox<>();
        jCBResponsable = new javax.swing.JComboBox<>();
        jBCrear = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear item");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("ID:");

        jLabel3.setText("Responsable:");

        jLabel4.setText("Tipo:");

        jCBTipo.setModel(modeloTipos);

        jCBResponsable.setModel(modeloEmpleados);

        jBCrear.setText("Crear");
        jBCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCrearMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFNombre)
                    .addComponent(jTFId)
                    .addComponent(jCBTipo, 0, 121, Short.MAX_VALUE)
                    .addComponent(jCBResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrear)
                    .addComponent(jBCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCrearMouseClicked
        if (esValido()){
            Long id=Long.parseLong(jTFId.getText());
            String nombre=jTFNombre.getText();
            Tipo tipo=modeloTipos.getObjeto(jCBTipo.getSelectedIndex());
            Empleado responsable=modeloEmpleados.getObjeto(jCBResponsable.getSelectedIndex());
            Item i=new Item(id,nombre,tipo,responsable,empleado);
            controladorItems.addElemento(i);
            dispose();
        }
    }//GEN-LAST:event_jBCrearMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jTFNombre.setText("");
        jTFId.setText("");
        jCBTipo.setSelectedIndex(-1);
        jCBResponsable.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JComboBox<String> jCBResponsable;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
