/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorItemsEmpleado;
import Controlador.ControladorItemsEquipo;
import Dominio.Empleado;
import Dominio.Equipo;
import Dominio.Item;
import Modelo.ModeloHistoricosItem;
import Modelo.ModeloItemsEmpleado;
import Modelo.ModeloItemsEquipo;
import javax.swing.JOptionPane;

/**
 *
 * @author mauro
 */
public class Responsable extends javax.swing.JFrame {
    
    private static Responsable responsable=null;

    private Empleado usuario;
    private Item itemUsuario;
    private Equipo equipo;
    private ModeloItemsEquipo modeloItemsEquipo=new ModeloItemsEquipo();
    private ModeloHistoricosItem modeloHistorico=new ModeloHistoricosItem();
    private ModeloItemsEmpleado modeloItemsRegistrados=new ModeloItemsEmpleado();
    
    private ControladorItemsEquipo controladorItemsEquipo;
    private ControladorItemsEmpleado controladorItemsEmpleado;
    
    
    public static Responsable getInstance(){
        if (responsable==null)responsable=new Responsable();
        return responsable;
    }
    private Responsable() {
        initComponents();
    }

    public void abrirVentana(Equipo equipo,Empleado usuario){
        setVisible(true);
        this.setLocationRelativeTo(null);
        this.equipo=equipo;
        modeloItemsEquipo.setLista(equipo);
        modeloItemsRegistrados.setLista(usuario);
        this.usuario=usuario;
        this.itemUsuario=usuario.getItem();   
        jTItemsRegistrados.setDefaultRenderer(Object.class, new RenderizadoCeldas(modeloItemsRegistrados));
        this.controladorItemsEquipo=new ControladorItemsEquipo(jTitemsEquipo);
        this.controladorItemsEmpleado=new ControladorItemsEmpleado(jTItemsRegistrados);
        cargarItem();
    }
    
    public void cargarItem(){
        if (itemUsuario!=null){
            jTFNombre.setText(itemUsuario.getNombre());
            jTFEstado.setText(itemUsuario.getEstadoActual().toString());
            jTFResponsable.setText(itemUsuario.getResponsable().toString());
            jTFTipo.setText(itemUsuario.getTipo().toString());
        }
        else{
            jTFNombre.setText("");
            jTFEstado.setText("");
            jTFResponsable.setText("");
            jTFTipo.setText("");       
        }
    }
    
    public void actualizarItem(){
        this.itemUsuario=usuario.getItem();
        cargarItem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTitemsEquipo = new javax.swing.JTable();
        jBCrearItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFTipo = new javax.swing.JTextField();
        jTFEstado = new javax.swing.JTextField();
        jTFResponsable = new javax.swing.JTextField();
        jBCambiarEstado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTItemsRegistrados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCambios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vista empleado");
        setMinimumSize(new java.awt.Dimension(578, 293));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTitemsEquipo.setModel(modeloItemsEquipo);
        jScrollPane1.setViewportView(jTitemsEquipo);

        jBCrearItem.setText("Crear item");
        jBCrearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBCrearItem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCrearItem)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Items", jPanel1);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Estado:");

        jLabel4.setText("Responsable:");

        jTFNombre.setEditable(false);
        jTFNombre.setBorder(null);

        jTFTipo.setEditable(false);
        jTFTipo.setBorder(null);

        jTFEstado.setEditable(false);
        jTFEstado.setBorder(null);

        jTFResponsable.setEditable(false);
        jTFResponsable.setBorder(null);

        jBCambiarEstado.setText("Cambiar estado");
        jBCambiarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCambiarEstadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jTFTipo)
                            .addComponent(jTFEstado)
                            .addComponent(jTFResponsable)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBCambiarEstado)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBCambiarEstado)
                .addContainerGap())
        );

        jTabbedPane1.addTab("item", jPanel2);

        jSplitPane1.setDividerLocation(250);

        jTItemsRegistrados.setModel(modeloItemsRegistrados);
        jTItemsRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTItemsRegistradosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTItemsRegistrados);

        jSplitPane1.setLeftComponent(jScrollPane3);

        jTCambios.setModel(modeloHistorico);
        jScrollPane2.setViewportView(jTCambios);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Cambios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCambiarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCambiarEstadoMouseClicked
        if (itemUsuario!=null){
            CambiarEstado.getInstance().abrirVentana(itemUsuario,usuario);
            modeloHistorico.fireTableDataChanged();
        }
        else
            JOptionPane.showMessageDialog(null, "Operación inválida");
        
    }//GEN-LAST:event_jBCambiarEstadoMouseClicked

    private void jBCrearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearItemActionPerformed
        CrearItem.getInstance().abrirVentana(controladorItemsEquipo,usuario,equipo.obtenerMiembros());
        modeloItemsRegistrados.fireTableDataChanged();
    }//GEN-LAST:event_jBCrearItemActionPerformed

    private void jTItemsRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTItemsRegistradosMouseClicked
        Item item=controladorItemsEmpleado.getElemento();
        item.setVisto();
        jTItemsRegistrados.repaint();
        modeloHistorico.setLista(item);
    }//GEN-LAST:event_jTItemsRegistradosMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Login.getInstance().abrirVentana();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCambiarEstado;
    private javax.swing.JButton jBCrearItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTCambios;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFResponsable;
    private javax.swing.JTextField jTFTipo;
    private javax.swing.JTable jTItemsRegistrados;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTitemsEquipo;
    // End of variables declaration//GEN-END:variables
}
